Repository JuliaGraphs/LightGraphs.jl, pull requests merged in 2018-10, with the labels that each got.

#1032 adding Dorogovtsev Mendes random graph generator
  src/LightGraphs.jl
  src/SimpleGraphs/SimpleGraphs.jl
  src/SimpleGraphs/generators/randgraphs.jl
  test/simplegraphs/generators/randgraphs.jl
Labels: enhancement, hacktoberfest

#1031 Add CompleteMultipartiteGraph and TuranGraph
  src/LightGraphs.jl
  src/SimpleGraphs/SimpleGraphs.jl
  src/SimpleGraphs/generators/staticgraphs.jl
  test/simplegraphs/generators/staticgraphs.jl
Labels: enhancement, hacktoberfest

#1044 Add ladder graphs
  src/LightGraphs.jl
  src/SimpleGraphs/SimpleGraphs.jl
  src/SimpleGraphs/generators/staticgraphs.jl
  test/simplegraphs/generators/staticgraphs.jl
Labels: hacktoberfest

#1047 Added a function rem_vertices!
  src/LightGraphs.jl
  src/SimpleGraphs/SimpleGraphs.jl
  src/SimpleGraphs/simpledigraph.jl
  src/SimpleGraphs/simplegraph.jl
  test/simplegraphs/simplegraphs.jl
Labels: hacktoberfest

#1049 Doctests for merge_vertices{!}
  src/operators.jl
Labels: doc, hacktoberfest

#1050 Doctests for union and symmetric_difference and cleanup for compute_s…
  src/operators.jl
Labels: doc, hacktoberfest

#1052 Doctests for some community features
  src/community/clustering.jl
  src/community/core-periphery.jl
Labels: doc, hacktoberfest

#1053 Include isomorphism docs and one more example
  docs/src/experimental.md
  src/Experimental/isomorphism.jl
Labels: doc, hacktoberfest

#1051 Doctest the k-core and friends methods
  src/degeneracy.jl
Labels: doc, hacktoberfest

#1055 Fix formatting of list in docs
  docs/src/index.md
Labels: doc, hacktoberfest

#1057 Example for the global clustering coefficient
  src/community/clustering.jl
Labels: doc, hacktoberfest

#1058 Examples for transitive closure and reduction
  src/digraph/transitivity.jl
Labels: doc, hacktoberfest

#1039 Dominating Set
  src/LightGraphs.jl
  src/Parallel/Parallel.jl
  src/Parallel/dominatingset/minimal_dom_set.jl
  src/Parallel/utils.jl
  src/dominatingset/degree_dom_set.jl
  src/dominatingset/minimal_dom_set.jl
  src/utils.jl
  test/dominatingset/degree_dom_set.jl
  test/dominatingset/minimal_dom_set.jl
  test/parallel/dominatingset/minimal_dom_set.jl
  test/parallel/runtests.jl
  test/runtests.jl
  test/utils.jl
Labels: hacktoberfest
