Repository JuliaGraphs/LightGraphs.jl, pull requests merged in 2018-08, with the labels that each got.

#981 Refactor isomorphism.jl to permit use of external algorithms
  src/Experimental/Experimental.jl
  src/Experimental/isomorphism.jl
  src/Experimental/vf2.jl
  test/experimental/isomorphism.jl
Labels: experimental

#984 Fix kruskal_mst function for working with abstract graphs
  src/spanningtrees/kruskal.jl
Labels: enhancement

#987 Threaded centrality
  src/Parallel/centrality/betweenness.jl
  src/Parallel/centrality/closeness.jl
  src/Parallel/centrality/radiality.jl
  src/Parallel/centrality/stress.jl
  test/parallel/centrality/betweenness.jl
  test/parallel/centrality/closeness.jl
  test/parallel/centrality/radiality.jl
  test/parallel/centrality/stress.jl
Labels: GSOC 2018
