Repository JuliaGraphs/LightGraphs.jl, pull requests merged in 2020-05, with the labels that each got.

#1418 moved parallel vertex subset code into VertexSubsets
  src/LightGraphs.jl
  src/Parallel/Parallel.jl
  src/Parallel/dominatingset/minimal_dom_set.jl
  src/Parallel/independentset/maximal_ind_set.jl
  src/Parallel/utils.jl
  src/Parallel/vertexcover/random_vertex_cover.jl
  src/VertexSubsets/VertexSubsets.jl
  src/VertexSubsets/degree_vertex_cover.jl
  src/VertexSubsets/maximal_ind_set.jl
  src/VertexSubsets/minimal_dom_set.jl
  src/VertexSubsets/parallel-maximal_ind_set.jl
  src/VertexSubsets/parallel-minimal_dom_set.jl
  src/VertexSubsets/parallel-random_vertex_cover.jl
  src/VertexSubsets/random_vertex_cover.jl
  src/VertexSubsets/threaded-maximal_ind_set.jl
  src/VertexSubsets/threaded-minimal_dom_set.jl
  src/VertexSubsets/threaded-random_vertex_cover.jl
  src/utils.jl
  test/VertexSubsets/parallel-maximal_ind_set.jl
  test/VertexSubsets/parallel-minimal_dom_set.jl
  test/VertexSubsets/parallel-random_vertex_cover.jl
  test/VertexSubsets/runtests.jl
  test/VertexSubsets/threaded-maximal_ind_set.jl
  test/VertexSubsets/threaded-minimal_dom_set.jl
  test/VertexSubsets/threaded-random_vertex_cover.jl
  test/parallel13/runtests.jl
  test/parallel13/utils.jl
  test/utils.jl
Labels: 1.4.0/2.0.0

#1422 Sbromberger/structure 2.0
  src/Experimental/isomorphism.jl
  src/Experimental/vf2.jl
  src/LightGraphs.jl
  src/Structure/Structure.jl
  src/Structure/edit_distance.jl
  src/Structure/isomorphism.jl
  src/Structure/vf2.jl
  src/deprecations13/edit_distance.jl
  test/Structure/edit_distance.jl
  test/Structure/isomorphism.jl
  test/Structure/runtests.jl
  test/deprecations13/experimental/experimental.jl
  test/deprecations13/experimental/isomorphism.jl
  test/runtests.jl
Labels: 1.4.0/2.0.0

#1424 bug fix in parallel kcore and correct indentation in issubset
  src/Degeneracy/kabirmadduri.jl
  src/SimpleGraphsCore/SimpleGraphsCore.jl
Labels: 1.4.0/2.0.0, bug, jsoc2020

#1413 [JSoC'20] Multithreaded Connected Components
  src/Connectivity/Connectivity.jl
  src/Connectivity/threaded_pointer_jumping.jl
  test/Connectivity/connectivity.jl
Labels: jsoc2020

#1428 weighted Katz
  src/Centrality/katz.jl
  test/Centrality/katz.jl
Labels: 1.4.0/2.0.0, enhancement
