Repository JuliaGraphs/LightGraphs.jl, pull requests merged in 2020-01, with the labels that each got.

#1170 Fix adjacency matrix for all types
  src/linalg/spectral.jl
  test/linalg/spectral.jl
Labels: bug, discussion

#1261 adding boruvka function and tests
  src/LightGraphs.jl
  src/spanningtrees/boruvka.jl
  test/runtests.jl
  test/spanningtrees/boruvka.jl
Labels: enhancement

#1281 improved performance of core_number - credit to @abhinavmehndiratta
  src/degeneracy.jl
Labels: efficiency / performance
