Repository JuliaGraphs/LightGraphs.jl, pull requests merged in 2020-03, with the labels that each got.

#1310 Sbromberger/new astar
  LICENSE.md
  src/Experimental/ShortestPaths/astar.jl
Labels: enhancement

#1340 fix Topological Sort
  src/Traversals/depthfirst.jl
  test/Traversals/depthfirst.jl
Labels: bug, efficiency / performance

#1335 parallel traversals and other fixes to Traversals.
  .gitignore
  src/Experimental/ShortestPaths/bfs.jl
  src/Parallel/traversals/bfs.jl
  src/Parallel/traversals/gdistances.jl
  src/Parallel/traversals/greedy_color.jl
  src/Traversals/Traversals.jl
  src/Traversals/breadthfirst.jl
  src/Traversals/depthfirst.jl
  src/Traversals/greedy_color.jl
  src/Traversals/randomwalks.jl
  src/Traversals/threaded_greedy_color.jl
  src/Traversals/threadedbreadthfirst.jl
  src/traversals13/bipartition.jl
  src/traversals13/dfs.jl
  src/traversals13/diffusion.jl
  src/traversals13/greedy_color.jl
  src/traversals13/maxadjvisit.jl
  src/traversals13/randomwalks.jl
  test/Traversals/bipartition.jl
  test/Traversals/breadthfirst.jl
  test/Traversals/depthfirst.jl
  test/Traversals/diffusion.jl
  test/Traversals/greedy_color.jl
  test/Traversals/maxadjvisit.jl
  test/Traversals/randomwalks.jl
  test/Traversals/runtests.jl
  test/Traversals/threaded_greedy_color.jl
  test/Traversals/threadedbreadthfirst.jl
  test/parallel/traversals/gdistances.jl
  test/traversals13/dfs.jl
Labels: efficiency / performance, enhancement

#1320 Friendship graph generator
  src/LightGraphs.jl
  src/SimpleGraphs/SimpleGraphs.jl
  src/SimpleGraphs/generators/staticgraphs.jl
  test/simplegraphs/generators/staticgraphs.jl
Labels: enhancement, waiting on author

#1367 Update ancient Dict syntax
  docs/src/persistence.md
Labels: doc

#1364 [WIP] Sbromberger/connectivity v1.4.0
  src/Connectivity/Connectivity.jl
  src/Connectivity/neighborhood_dists.jl
  src/LightGraphs.jl
  src/connectivity.jl
  src/operators.jl
  test/Connectivity/connectivity.jl
  test/Connectivity/runtests.jl
  test/runtests.jl
Labels: 1.4.0/2.0.0
