Repository JuliaGraphs/LightGraphs.jl, pull requests merged in 2020-02, with the labels that each got.

#1278 visitor functions
  src/Experimental/Experimental.jl
  src/Experimental/ShortestPaths/ShortestPaths.jl
  src/Experimental/ShortestPaths/bfs.jl
  src/Experimental/Traversals/Traversals.jl
  src/Experimental/Traversals/bfs.jl
  src/Experimental/Traversals/dfs.jl
  test/experimental/experimental.jl
  test/experimental/shortestpaths.jl
  test/experimental/traversals.jl
Labels: efficiency / performance, enhancement, experimental, waiting for review

#1285 documentation typo fixes
  src/community/modularity.jl
Labels: doc

#1292 Parameterize connectivity tests
  test/connectivity.jl
Labels: CI / tests
